# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageInterrogatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListInterrogators = channel.unary_unary(
                '/interrogator.ImageInterrogator/ListInterrogators',
                request_serializer=services__pb2.InterrogatorListingRequest.SerializeToString,
                response_deserializer=services__pb2.InterrogatorListing.FromString,
                _registered_method=True)
        self.InterrogateImage = channel.unary_unary(
                '/interrogator.ImageInterrogator/InterrogateImage',
                request_serializer=services__pb2.InterrogationRequest.SerializeToString,
                response_deserializer=services__pb2.ImageTagResults.FromString,
                _registered_method=True)
        self.InterrogatorParameters = channel.unary_unary(
                '/interrogator.ImageInterrogator/InterrogatorParameters',
                request_serializer=services__pb2.InterrogatorParamRequest.SerializeToString,
                response_deserializer=services__pb2.InterrogatorParamResponse.FromString,
                _registered_method=True)


class ImageInterrogatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListInterrogators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InterrogateImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InterrogatorParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageInterrogatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListInterrogators': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInterrogators,
                    request_deserializer=services__pb2.InterrogatorListingRequest.FromString,
                    response_serializer=services__pb2.InterrogatorListing.SerializeToString,
            ),
            'InterrogateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.InterrogateImage,
                    request_deserializer=services__pb2.InterrogationRequest.FromString,
                    response_serializer=services__pb2.ImageTagResults.SerializeToString,
            ),
            'InterrogatorParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.InterrogatorParameters,
                    request_deserializer=services__pb2.InterrogatorParamRequest.FromString,
                    response_serializer=services__pb2.InterrogatorParamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interrogator.ImageInterrogator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('interrogator.ImageInterrogator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageInterrogator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListInterrogators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interrogator.ImageInterrogator/ListInterrogators',
            services__pb2.InterrogatorListingRequest.SerializeToString,
            services__pb2.InterrogatorListing.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InterrogateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interrogator.ImageInterrogator/InterrogateImage',
            services__pb2.InterrogationRequest.SerializeToString,
            services__pb2.ImageTagResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InterrogatorParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interrogator.ImageInterrogator/InterrogatorParameters',
            services__pb2.InterrogatorParamRequest.SerializeToString,
            services__pb2.InterrogatorParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
